=== philgei/AdLerWorldTransferFile/v0.3/schema0_3.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "fileVersion": {
      "type": "string"
    },
    "amgVersion": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "enum": ["de", "en"]
    },
    "world": {
      "type": "object",
      "properties": {
        "lmsElementIdentifier": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["type", "value"]
        },
        "worldName": {
          "type": "string"
        },
        "worldDescription": {
          "type": "string"
        },
        "worldGoals": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "spaces": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "spaceId": {
                "type": "integer"
              },
              "lmsElementIdentifier": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["type", "value"]
              },
              "spaceName": {
                "type": "string"
              },
              "spaceDescription": {
                "type": "string"
              },
              "spaceGoals": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "spaceContents": {
                "type": "array",
                "items": {
                  "type": "integer"
                },
                "minItems": 1
              },

              "requiredPointsToComplete": {
                "type": "integer"
              },
              "requiredSpacesToEnter": {
                "type": "string"
              }
            },
            "required": [
              "spaceId",
              "lmsElementIdentifier",
              "spaceDescription",
              "spaceGoals",
              "spaceContents",
              "requiredSpacesToEnter",
              "spaceName"
            ]
          },
          "minItems": 1
        },
        "elements": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "elementId": {
                "type": "integer"
              },
              "lmsElementIdentifier": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["type", "value"]
              },
              "elementName": {
                "type": "string"
              },
              "elementDescription": {
                "type": "string"
              },
              "elementGoals": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "elementCategory": {
                "type": "string"
              },
              "elementFileType": {
                "type": "string"
              },
              "elementPoints": {
                "type": "integer"
              }
            },
            "required": [
              "elementId",
              "lmsElementIdentifier",
              "elementCategory",
              "elementFileType",
              "elementPoints",
              "elementName"
            ],
            "minItems": 1
          }
        }
      },
      "required": ["lmsElementIdentifier", "spaces", "elements", "worldName"]
    }
  },
  "required": ["fileVersion", "world"]
}

=== philgei/AdLerWorldTransferFile/v0.3/AdLerWorldTransfer0_3.json
{
  "fileVersion": "0.3",
  "amgVersion": "1.0",
  "author": "Peter",
  "language": "de",
  "world": {
    "lmsElementIdentifier": {
      "type": "idNumber",
      "value": "123456789randomID"
    },
    "worldName": "Name der Welt",
    "worldDescription": "Beschreibung der Welt",
    "worldGoals": ["Ziel 1", "Ziel 2"],
    "spaces": [
      {
        "spaceId": 1,
        "lmsElementIdentifier": {
          "type": "idNumber",
          "value": "123456789randomID"
        },
        "spaceName": "Name des Lernraums",
        "spaceDescription": "Beschreibung des Lernraums",
        "spaceGoals": ["Ziel 1", "Ziel 2"],
        "spaceContents": [1, 2, 3],
        "requiredPointsToComplete": 100,
        "requiredSpacesToEnter": "(5)v((7)^(4))"
      }
    ],
    "elements": [
      {
        "elementId": 1,
        "lmsElementIdentifier": {
          "type": "moduleName",
          "value": "Ein wunderschöner, für den Nutzer sichtbarer, String"
        },
        "elementName": "Name des Elements",
        "elementDescription": "Beschreibung des Lernelements",
        "elementGoals": ["Ziel 1", "Ziel 2"],
        "elementCategory": "image",
        "elementFileType": "image:png",
        "elementPoints": 123
      }
    ]
  }
}
